# Generated by Django 5.0.6 on 2024-10-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userprofile_first_name_userprofile_nick_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='nick_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
        migrations.AddField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='detail',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='flaw',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default='Anonymous', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='history',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default='Anonymous', max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='prefer_items',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='surname',
            field=models.CharField(default='Anonymous', max_length=30),
        ),
    ]
