# Generated by Django 5.0.6 on 2024-10-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_userprofile_nick_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='Anonymous', max_length=30),
        ),
    ]
