# Generated by Django 5.0.6 on 2024-10-14 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_category_alter_userprofile_phone_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='preferences',
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like_electronics', models.BooleanField(default=False)),
                ('is_like_clothing', models.BooleanField(default=False)),
                ('is_like_beauty_accessories', models.BooleanField(default=False)),
                ('is_like_books', models.BooleanField(default=False)),
                ('is_like_kitchenware', models.BooleanField(default=False)),
                ('is_like_petcare', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferences',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.userpreference'),
        ),
    ]
