# Generated by Django 5.0.6 on 2024-10-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_userprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dorm',
            field=models.CharField(default='Anonymous', max_length=30),
        ),
        migrations.RemoveField(
            model_name='post',
            name='dorm',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RemoveField(
            model_name='verify',
            name='post',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='verify',
        ),
        migrations.RemoveField(
            model_name='verify',
            name='verifier',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='history',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='prefer_items',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Dorm',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Verify',
        ),
    ]
