# Generated by Django 5.0.6 on 2024-10-15 18:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_userprofile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostGiver',
            fields=[
                ('post_ID', models.AutoField(primary_key=True, serialize=False)),
                ('stuff_name', models.CharField(max_length=50)),
                ('categories', models.CharField(choices=[('หนังสือ', 'หนังสือ'), ('เครื่องครัว', 'เครื่องครัว'), ('อุปกรณ์เสริมสวย', 'อุปกรณ์เสริมสวย'), ('เครื่องใช้ไฟฟ้า', 'เครื่องใช้ไฟฟ้า'), ('เฟอร์นิเจอร์', 'เฟอร์นิเจอร์'), ('อุปกรณ์สำหรับสัตว์เลี้ยง', 'อุปกรณ์สำหรับสัตว์เลี้ยง'), ('เสื้อผ้า', 'เสื้อผ้า')], max_length=50)),
                ('stuff_picture', models.ImageField(blank=True, null=True, upload_to='stuff_picture/')),
                ('description', models.TextField()),
                ('defect', models.CharField(max_length=50)),
                ('place', models.TextField()),
                ('date_limit', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dorm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PostReceiver',
            fields=[
                ('post_ID', models.AutoField(primary_key=True, serialize=False)),
                ('stuff_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('categories', models.CharField(choices=[('หนังสือ', 'หนังสือ'), ('เครื่องครัว', 'เครื่องครัว'), ('อุปกรณ์เสริมสวย', 'อุปกรณ์เสริมสวย'), ('เครื่องใช้ไฟฟ้า', 'เครื่องใช้ไฟฟ้า'), ('เฟอร์นิเจอร์', 'เฟอร์นิเจอร์'), ('อุปกรณ์สำหรับสัตว์เลี้ยง', 'อุปกรณ์สำหรับสัตว์เลี้ยง'), ('เสื้อผ้า', 'เสื้อผ้า')], max_length=50)),
                ('defect', models.CharField(max_length=50)),
                ('place', models.TextField()),
                ('date_limit', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dorm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile')),
            ],
        ),
    ]
