# Generated by Django 5.0.6 on 2024-10-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_userprofile_dorm_remove_post_dorm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_ID',
            field=models.AutoField(default='not defined', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
