# Generated by Django 5.0.6 on 2024-10-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_postgiver_postreceiver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postgiver',
            old_name='dorm',
            new_name='user_profile',
        ),
        migrations.AlterField(
            model_name='postgiver',
            name='defect',
            field=models.CharField(choices=[('ไม่มี', 'ไม่มี'), ('น้อย', 'น้อย'), ('ปานกลาง', 'ปานกลาง'), ('มาก', 'มาก')], max_length=50),
        ),
    ]
