# Generated by Django 5.0.6 on 2024-10-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_userprofile_user_id_userprofile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='student_ID',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
