# Generated by Django 5.0.6 on 2024-10-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_matchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='postgiver',
            name='is_matched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postreceiver',
            name='is_matched',
            field=models.BooleanField(default=False),
        ),
    ]
