# Generated by Django 5.0.6 on 2024-10-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_userprofile_id_alter_userprofile_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_ID',
            field=models.AutoField(default='none', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='student_ID',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
