# Generated by Django 5.0.6 on 2024-10-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_userprofile_user_id_alter_userprofile_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_ID',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
