# Generated by Django 5.1.2 on 2024-10-18 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_alter_matchhistory_giver_post_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MatchHistory",
        ),
    ]
