# Generated by Django 5.0.6 on 2024-10-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_userprofile_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
