# Generated by Django 5.1.2 on 2024-10-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_delete_matchhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="postgiver",
            name="is_verify",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="postreceiver",
            name="is_verify",
            field=models.BooleanField(default=False),
        ),
    ]
