# Generated by Django 5.1.2 on 2024-10-19 12:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_postgiver_is_verify_postreceiver_is_verify"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchedPost",
            fields=[
                ("match_ID", models.AutoField(primary_key=True, serialize=False)),
                ("match_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "giver_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="giver_matches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "giver_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.postgiver",
                    ),
                ),
                (
                    "receiver_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receiver_matches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "receiver_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.postreceiver",
                    ),
                ),
            ],
        ),
    ]
