# Generated by Django 5.1.2 on 2024-10-19 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0013_matchedpost"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MatchedPost",
        ),
    ]
