# Generated by Django 5.1.2 on 2024-10-19 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0016_matchpost_delete_matchedpost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="matchpost",
            name="is_confirmed",
        ),
    ]
