# Generated by Django 5.1.2 on 2024-10-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0017_remove_matchpost_is_confirmed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postgiver",
            name="is_verify",
        ),
        migrations.RemoveField(
            model_name="postreceiver",
            name="is_verify",
        ),
        migrations.AddField(
            model_name="matchpost",
            name="is_confirm",
            field=models.BooleanField(default=False),
        ),
    ]
