# Generated by Django 5.1.2 on 2024-10-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0018_remove_postgiver_is_verify_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="postreceiver",
            name="is_confirm",
            field=models.BooleanField(default=False),
        ),
    ]
