# Generated by Django 5.1.2 on 2024-10-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0020_postgiver_is_confirm"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="matchpost",
            name="is_confirm",
        ),
        migrations.AddField(
            model_name="matchpost",
            name="is_both_confirm",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="matchpost",
            name="is_giver_confirm",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="matchpost",
            name="is_receiver_confirm",
            field=models.BooleanField(default=False),
        ),
    ]
