# Generated by Django 5.1.2 on 2024-10-27 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0021_remove_matchpost_is_confirm_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="matchpost",
            name="is_both_confirm",
        ),
    ]
